### ISSUE TITLE
Theme for our site?

### ISSUE THREAD

**Issue by nikzei** [codeforamerica/code_for_vallejo#26]
Thoughts?
I can play around with installation, etc. if you guys think that it could work:
https://github.com/jeromelachaud/freelancer-theme

**Comment by andrewschneider** [comment]
It looks good to me. I'll put together a list of steps you'll need to get the site running locally and we can go through it together. I'm not super familiar with setting up jekyll themes but can give you some pointers (and obviously ask me questions -- if I can't help there are other people here better at jekyll than I am).

**Comment by nikzei** [comment]
Cool - thanks. I'm up for learning through working on this site so that all sounds good!

**Comment by nikzei** [comment]
This is a bootstrap theme but we're not using bootstrap.  Might be too complicated/not worth it . . .
